Repository o1-labs/o1js, pull requests merged in 2024-01, with the labels that each got.

#1356 Exercise more complicated zkApps with CI checks.
  .github/actions/live-tests-shared/action.yml
  .github/workflows/live-tests.yml
  run-ci-live-tests.sh
  run-ci-tests.sh
  src/examples/zkapps/dex/arbitrary_token_interaction.ts
  src/examples/zkapps/dex/dex-with-actions.ts
  src/examples/zkapps/dex/dex.ts
  src/examples/zkapps/dex/happy-path-with-actions.ts
  src/examples/zkapps/dex/happy-path-with-proofs.ts
  src/examples/zkapps/dex/run.ts
  src/examples/zkapps/dex/run_live.ts
  src/examples/zkapps/dex/upgradability.ts
Labels: e2e-tests

#1387 (WIP) Add support for mainnet.
  CHANGELOG.md
  package-lock.json
  package.json
  src/lib/account_update.ts
  src/lib/mina.ts
  src/mina-signer/MinaSigner.ts
  src/mina-signer/src/TSTypes.ts
  src/mina-signer/src/random-transaction.ts
  src/mina-signer/src/sign-legacy.ts
  src/mina-signer/src/sign-legacy.unit-test.ts
  src/mina-signer/src/sign-zkapp-command.ts
  src/mina-signer/src/sign-zkapp-command.unit-test.ts
  src/mina-signer/src/signature.ts
Labels: berkeley-mainnet

#1389 Bump mina-signer and export NetworkId type.
  src/mina-signer/index.d.ts
  src/mina-signer/package-lock.json
  src/mina-signer/package.json
Labels: berkeley-mainnet

#1382 Create README.md for SHA-256 hashing example
  src/examples/zkapps/hashing/README.md
Labels: docs
